clc;

NAMES = { 'test_gc', 'print_recursive' };

disp('---------------------------------------------------------');
SRCS = [...
  '../src/GenericContainer.cc ', ...
  '../src/GenericContainerCollapse.cc ', ...
  '../src/GenericContainerPromote.cc ', ...
  '../src/GenericContainerSerialize.cc ', ...
  '../src/GenericContainerSupport.cc ', ...
  '../src/GenericContainerTables.cc ', ...
  '../src_json_interface/from_json.cc ', ...
  '../src_json_interface/to_json.cc ', ...
  '../src_json_interface/jsonParser.tab.cc ', ...
  '../src_json_interface/jsonLexer.cc ', ...
  '../src_toml_interface/from_toml.cc ', ...
  '../src_toml_interface/to_toml.cc ', ...
  '../src_yaml_interface/from_yaml.cc ', ...
  '../src_yaml_interface/to_yaml.cc ', ...
  'GenericContainerInterface_matlab.cc' ...
];

for k=1:2
  N=NAMES{k};
  fprintf(1,'Compiling: %s\n',N);

  CMD = ['mex -I../src -I../include -I../include/GenericContainer -I../src_yaml_interface -output ',N,' -largeArrayDims mex_',N,'.cc ', SRCS];
  if isunix
    if ismac
      CMD = [CMD, ' -lstdc++ CXXFLAGS="\$CXXFLAGS -std=c++17 -Wall -O2 -g"'];
    else
      CMD = [CMD, ' -lstdc++ CXXFLAGS="\$CXXFLAGS -std=c++17 -Wall -O2 -g"'];
    end
  elseif ispc
  end
  disp(CMD);
  eval(CMD);
end
disp('----------------------- DONE ----------------------------');
